- source/docs/06_guides/03_partner_guide.cs.md
- source/docs/06_guides/03_partner_guide.http.md
- source/docs/06_guides/03_partner_guide.java.md
- source/docs/06_guides/03_partner_guide.php.md
- source/docs/06_guides/03_partner_guide.py.md
- source/docs/06_guides/03_partner_guide.rb.md
@jamesshedden This article was removed from the help docs because it was less helpful than this section of the dev docs, so it didn't make sense to divert people away from here! Could you review please?
> Remove old partner info link

- source/docs/02_api_libraries/03_webhooks/02_receiving_webhooks/02_receiving_webhooks.js.md
@jackfranklin Thanks for taking a look at this one! :boom: 
& Thanks to @jhiver for letting us know!
> Use correct data in Node web hook example

- gulpfile.js
- source/hyper-schema.json
Put the GoCardless hyper schema in the public directory :tada: @samjewell could you review?
> Add hyper schema

- source/docs/01_overview/01_introduction.md
> We call it Pro, not Enterprise

- source/javascripts/toc-nav/toc-nav-directive.js
- source/stylesheets/components/section-header.scss
- source/stylesheets/modules/headers.scss
- source/stylesheets/variables.scss
@greysteil, same as in enterprise
> Add github style hover links to headers

- source/docs/01_overview/01_introduction.md
Not keen on the current intro wording. These docs should be really appealing to developers. I feel like this phrasing is more to the point.
@anothertompetty Says yes on this.
> Improve wording on intro

- source/docs/01_overview/01_introduction.md
> Another tweak to intro text

- source/docs/01_overview/01_introduction.md
> this time branched from up-to-date dev

- source/docs/01_overview/03_storing_ids.md
That. Need to notify developers of this, and we shouldn't actually make any changes until June / July, but the earlier this is documented the better.
> Increase ID length to 255

- source/docs/06_guides/02_first_payment.js.md
- source/docs/06_guides/02_first_payment.php.md
- source/docs/06_guides/02_first_payment.py.md
- source/docs/06_guides/02_first_payment.rb.md
These weren’t being parsed correctly!
@Ken-Lo could you review please? This should fix what you've mentioned in https://github.com/gocardless/api-docs/pull/64
> Fix broken example domains

- source/docs/01_overview/01_introduction.md
> Add a notice calling for beta testers for the Pro API

- source/docs/06_guides/03_partner_guide.http.md
Included clearer examples for partner exchange of authorisation code
for access token, in particular the example access token.
@jacobpgn Please review.
> Improved partner authorisation documentation

- source/docs/06_guides/03_partner_guide.http.md
> Adding one space indentation to this block of code

- source/docs/01_overview/05_support/03_contact_us.md
@lewisblackwood Can I get a review please? :cake:
> Update support details

- source/docs/02_api_libraries/01_api_libraries/01_api_libraries.cs.md
@lewisblackwood :disappointed_relieved: Review please?
> Deprecate .net lib

- source/docs/02_api_libraries/01_api_libraries/01_api_libraries.http.md
@lewisblackwood :sweet_potato:, :+1: ?
> Remove .NET lib install guide

- source/docs/06_guides/02_first_payment.rb.md
found by merchant who emailed in
@jackfranklin Hi Jack, can you please take a look?
> fixing ruby code in dev docs

- source/docs/01_overview/01_introduction.md
- source/layouts/header.html
- source/stylesheets/components/deprecation-warning.scss
- source/stylesheets/components/site-frame.scss
- source/stylesheets/components/site-header.scss
- source/stylesheets/variables.scss
Lifted from the Pro docs - @greysteil, could you review?
_Before_
_After_
> Shout about the new API!

- circle.yml
> Deploy both staging and production from DEV branch

- circle.yml
As used at https://github.com/gocardless/legacy-api-docs/blob/master/s3_website.yml#L3
@timrogers pls 💟
> Use correct env variable for specifying s3 deploy bucket
